
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "APIService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://academic.research.microsoft.com/api.svc?wsdl")
public class APIService
    extends Service
{

    private final static URL APISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.APIService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.APIService.class.getResource(".");
            url = new URL(baseUrl, "http://academic.research.microsoft.com/api.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://academic.research.microsoft.com/api.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APISERVICE_WSDL_LOCATION = url;
    }

    public APIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public APIService() {
        super(APISERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "APIService"));
    }

    /**
     * 
     * @return
     *     returns IAPIService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAPIService")
    public IAPIService getBasicHttpBindingIAPIService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAPIService"), IAPIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAPIService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAPIService")
    public IAPIService getBasicHttpBindingIAPIService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAPIService"), IAPIService.class, features);
    }

}
