
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.research.AuthorResponse;
import com.microsoft.research.DomainResponse;
import com.microsoft.research.PublicationResponse;
import com.microsoft.research.Request;
import com.microsoft.research.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IAPIService", targetNamespace = "http://research.microsoft.com")
@XmlSeeAlso({
    com.microsoft.research.ObjectFactory.class,
    org.datacontract.schemas._2004._07.libra_service.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface IAPIService {


    /**
     * 
     * @return
     *     returns com.microsoft.research.DomainResponse
     */
    @WebMethod(operationName = "GetDomainList", action = "http://research.microsoft.com/IAPIService/GetDomainList")
    @WebResult(name = "GetDomainListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetDomainList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetDomainList")
    @ResponseWrapper(localName = "GetDomainListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetDomainListResponse")
    public DomainResponse getDomainList();

    /**
     * 
     * @param domainID
     * @return
     *     returns com.microsoft.research.DomainResponse
     */
    @WebMethod(operationName = "GetSubDomainList", action = "http://research.microsoft.com/IAPIService/GetSubDomainList")
    @WebResult(name = "GetSubDomainListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetSubDomainList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetSubDomainList")
    @ResponseWrapper(localName = "GetSubDomainListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetSubDomainListResponse")
    public DomainResponse getSubDomainList(
        @WebParam(name = "domainID", targetNamespace = "http://research.microsoft.com")
        Long domainID);

    /**
     * 
     * @param request
     * @return
     *     returns com.microsoft.research.Response
     */
    @WebMethod(operationName = "Search", action = "http://research.microsoft.com/IAPIService/Search")
    @WebResult(name = "SearchResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "Search", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.SearchResponse")
    public Response search(
        @WebParam(name = "request", targetNamespace = "http://research.microsoft.com")
        Request request);

    /**
     * 
     * @param domainId
     * @param subDomainId
     * @return
     *     returns com.microsoft.research.AuthorResponse
     */
    @WebMethod(operationName = "GetMostViewedAuthorList", action = "http://research.microsoft.com/IAPIService/GetMostViewedAuthorList")
    @WebResult(name = "GetMostViewedAuthorListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetMostViewedAuthorList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetMostViewedAuthorList")
    @ResponseWrapper(localName = "GetMostViewedAuthorListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetMostViewedAuthorListResponse")
    public AuthorResponse getMostViewedAuthorList(
        @WebParam(name = "domainId", targetNamespace = "http://research.microsoft.com")
        Long domainId,
        @WebParam(name = "subDomainId", targetNamespace = "http://research.microsoft.com")
        Long subDomainId);

    /**
     * 
     * @param domainId
     * @param subDomainId
     * @return
     *     returns com.microsoft.research.PublicationResponse
     */
    @WebMethod(operationName = "GetMostViewedPublicationList", action = "http://research.microsoft.com/IAPIService/GetMostViewedPublicationList")
    @WebResult(name = "GetMostViewedPublicationListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetMostViewedPublicationList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetMostViewedPublicationList")
    @ResponseWrapper(localName = "GetMostViewedPublicationListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetMostViewedPublicationListResponse")
    public PublicationResponse getMostViewedPublicationList(
        @WebParam(name = "domainId", targetNamespace = "http://research.microsoft.com")
        Long domainId,
        @WebParam(name = "subDomainId", targetNamespace = "http://research.microsoft.com")
        Long subDomainId);

    /**
     * 
     * @param doi
     * @return
     *     returns com.microsoft.research.PublicationResponse
     */
    @WebMethod(operationName = "GetPublicationByDOI", action = "http://research.microsoft.com/IAPIService/GetPublicationByDOI")
    @WebResult(name = "GetPublicationByDOIResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetPublicationByDOI", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetPublicationByDOI")
    @ResponseWrapper(localName = "GetPublicationByDOIResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetPublicationByDOIResponse")
    public PublicationResponse getPublicationByDOI(
        @WebParam(name = "doi", targetNamespace = "http://research.microsoft.com")
        String doi);

    /**
     * 
     * @return
     *     returns com.microsoft.research.AuthorResponse
     */
    @WebMethod(operationName = "GetLatestUpdatedAuthorList", action = "http://research.microsoft.com/IAPIService/GetLatestUpdatedAuthorList")
    @WebResult(name = "GetLatestUpdatedAuthorListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetLatestUpdatedAuthorList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetLatestUpdatedAuthorList")
    @ResponseWrapper(localName = "GetLatestUpdatedAuthorListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetLatestUpdatedAuthorListResponse")
    public AuthorResponse getLatestUpdatedAuthorList();

    /**
     * 
     * @return
     *     returns com.microsoft.research.PublicationResponse
     */
    @WebMethod(operationName = "GetLatestUpdatedPublicationList", action = "http://research.microsoft.com/IAPIService/GetLatestUpdatedPublicationList")
    @WebResult(name = "GetLatestUpdatedPublicationListResult", targetNamespace = "http://research.microsoft.com")
    @RequestWrapper(localName = "GetLatestUpdatedPublicationList", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetLatestUpdatedPublicationList")
    @ResponseWrapper(localName = "GetLatestUpdatedPublicationListResponse", targetNamespace = "http://research.microsoft.com", className = "com.microsoft.research.GetLatestUpdatedPublicationListResponse")
    public PublicationResponse getLatestUpdatedPublicationList();

}
